created Radio group component
Groww/frontatish pull request #102
Opened 2021-05-09 15:13 UTC by harivikneshs

Lets user to wrap up multiple radio buttons without worrying about onClick listeners and getting selected item value.

2021-05-13 11:32 UTC, vinitraj10 commented
@harivikneshs can you add some screenshots how the component is looking!!

2021-05-13 11:41 UTC, vinitraj10 requested changes
@harivikneshs  Please checkout other components docs and write doc for this too,let me know for any help

2021-05-21 08:38 UTC, vinitraj10 approved these changes

2021-05-27 18:00 UTC, amanBhawsar requested changes

2021-06-25 05:22 UTC, vinitraj10 approved these changes

2021-06-25 05:23 UTC, merged