Feature/swipable modal
Groww/frontatish pull request #95
Opened 2021-05-04 06:35 UTC by Akash-Kait

Added swipeable modal feature

2021-05-13 11:37 UTC, vinitraj10 commented
@Akash-Kait  please update some screenshot/video of the component you have made

2021-05-13 11:39 UTC, vinitraj10 requested changes
@Akash-Kait please create documentation too for this component,please check how other component docs has been written

2021-05-13 11:39 UTC, vinitraj10 commented on .eslintrc.js
> +      'error',
why this config added??

2021-05-19 11:58 UTC, Akash-Kait commented on .eslintrc.js
> +      'error',
end of line error for windows.

2021-05-21 08:48 UTC, Akash-Kait commented
> @Akash-Kait please create documentation too for this component,please check how other component docs has been written

Done

2021-05-21 08:49 UTC, Akash-Kait commented
> @Akash-Kait please update some screenshot/video of the component you have made

Done

2021-07-01 12:49 UTC, closed without merging